/**
 * This file will be auto-generated by Supabase CLI
 * Run: pnpm db:types
 *
 * For now, we'll define basic types manually
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      customers: {
        Row: {
          id: string
          full_name: string
          phone_number: string
          email: string | null
          date_of_birth: string | null
          address: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          phone_number: string
          email?: string | null
          date_of_birth?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          phone_number?: string
          email?: string | null
          date_of_birth?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      cards: {
        Row: {
          uid: string
          customer_id: string | null
          balance: number
          status: 'active' | 'inactive' | 'lost' | 'stolen'
          pin_hash: string
          daily_limit: number
          issued_at: string
          last_used_at: string | null
          expires_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          uid: string
          customer_id?: string | null
          balance?: number
          status?: 'active' | 'inactive' | 'lost' | 'stolen'
          pin_hash: string
          daily_limit?: number
          issued_at?: string
          last_used_at?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          uid?: string
          customer_id?: string | null
          balance?: number
          status?: 'active' | 'inactive' | 'lost' | 'stolen'
          pin_hash?: string
          daily_limit?: number
          issued_at?: string
          last_used_at?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      branches: {
        Row: {
          id: string
          name: string
          code: string
          location: string | null
          phone: string | null
          email: string | null
          manager_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          code: string
          location?: string | null
          phone?: string | null
          email?: string | null
          manager_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          code?: string
          location?: string | null
          phone?: string | null
          email?: string | null
          manager_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      staff: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          role: 'admin' | 'branch_manager' | 'cashier'
          branch_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          phone?: string | null
          role: 'admin' | 'branch_manager' | 'cashier'
          branch_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          role?: 'admin' | 'branch_manager' | 'cashier'
          branch_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          card_uid: string
          type: 'purchase' | 'top_up' | 'adjustment' | 'refund'
          amount: number
          balance_before: number
          balance_after: number
          branch_id: string | null
          staff_id: string | null
          payment_method: 'mtn' | 'airtel' | 'cash' | 'system' | null
          payment_reference: string | null
          status: 'pending' | 'completed' | 'failed' | 'cancelled'
          description: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          card_uid: string
          type: 'purchase' | 'top_up' | 'adjustment' | 'refund'
          amount: number
          balance_before: number
          balance_after: number
          branch_id?: string | null
          staff_id?: string | null
          payment_method?: 'mtn' | 'airtel' | 'cash' | 'system' | null
          payment_reference?: string | null
          status?: 'pending' | 'completed' | 'failed' | 'cancelled'
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          card_uid?: string
          type?: 'purchase' | 'top_up' | 'adjustment' | 'refund'
          amount?: number
          balance_before?: number
          balance_after?: number
          branch_id?: string | null
          staff_id?: string | null
          payment_method?: 'mtn' | 'airtel' | 'cash' | 'system' | null
          payment_reference?: string | null
          status?: 'pending' | 'completed' | 'failed' | 'cancelled'
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      top_ups: {
        Row: {
          id: string
          transaction_id: string | null
          card_uid: string
          amount: number
          source: string
          payment_provider: 'mtn' | 'airtel' | 'cash' | 'system'
          phone_number: string
          payment_reference: string | null
          status: 'pending' | 'completed' | 'failed' | 'cancelled'
          callback_data: Json | null
          initiated_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          transaction_id?: string | null
          card_uid: string
          amount: number
          source: string
          payment_provider: 'mtn' | 'airtel' | 'cash' | 'system'
          phone_number: string
          payment_reference?: string | null
          status?: 'pending' | 'completed' | 'failed' | 'cancelled'
          callback_data?: Json | null
          initiated_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          transaction_id?: string | null
          card_uid?: string
          amount?: number
          source?: string
          payment_provider?: 'mtn' | 'airtel' | 'cash' | 'system'
          phone_number?: string
          payment_reference?: string | null
          status?: 'pending' | 'completed' | 'failed' | 'cancelled'
          callback_data?: Json | null
          initiated_at?: string
          completed_at?: string | null
        }
      }
    }
    Views: {}
    Functions: {
      process_purchase: {
        Args: {
          p_card_uid: string
          p_amount: number
          p_branch_id: string
          p_staff_id: string
          p_description?: string
        }
        Returns: Json
      }
      process_top_up: {
        Args: {
          p_card_uid: string
          p_amount: number
          p_payment_provider: string
          p_payment_reference: string
          p_phone_number: string
          p_source?: string
        }
        Returns: Json
      }
      get_dashboard_stats: {
        Args: {
          p_branch_id?: string
          p_start_date?: string
          p_end_date?: string
        }
        Returns: Json
      }
    }
    Enums: {}
  }
}
